import { Streamer } from './types';

export const dummyStreamers: Streamer[] = [
  // 라이브 중인 스트리머들
  {
    id: '1',
    platform: 'chzzk',
    channelId: 'abc123',
    name: '우왁굳',
    profileImage: 'https://via.placeholder.com/100x100/00C853/ffffff?text=W',
    isLive: true,
    title: '오늘도 열심히 방송합니다~',
    thumbnail: 'https://via.placeholder.com/320x180/1a1a2e/ffffff?text=LIVE',
    viewerCount: 15420,
    category: '토크/캠방',
  },
  {
    id: '2',
    platform: 'soop',
    channelId: 'def456',
    name: '침착맨',
    profileImage: 'https://via.placeholder.com/100x100/2196F3/ffffff?text=C',
    isLive: true,
    title: '금요일 침투부 방송',
    thumbnail: 'https://via.placeholder.com/320x180/16213e/ffffff?text=LIVE',
    viewerCount: 23150,
    category: '토크/캠방',
  },
  {
    id: '3',
    platform: 'chzzk',
    channelId: 'ghi789',
    name: '릴파',
    profileImage: 'https://via.placeholder.com/100x100/00C853/ffffff?text=L',
    isLive: true,
    title: '노래 연습 중~ 🎵',
    thumbnail: 'https://via.placeholder.com/320x180/0f3460/ffffff?text=LIVE',
    viewerCount: 8930,
    category: '음악',
  },
  {
    id: '4',
    platform: 'soop',
    channelId: 'jkl012',
    name: '풍월량',
    profileImage: 'https://via.placeholder.com/100x100/2196F3/ffffff?text=P',
    isLive: true,
    title: '게임 방송 ㄱㄱ',
    thumbnail: 'https://via.placeholder.com/320x180/1a1a2e/ffffff?text=LIVE',
    viewerCount: 5620,
    category: '게임',
  },
  // 오프라인 스트리머들
  {
    id: '5',
    platform: 'chzzk',
    channelId: 'mno345',
    name: '아이네',
    profileImage: 'https://via.placeholder.com/100x100/00C853/ffffff?text=I',
    isLive: false,
  },
  {
    id: '6',
    platform: 'soop',
    channelId: 'pqr678',
    name: '주르르',
    profileImage: 'https://via.placeholder.com/100x100/2196F3/ffffff?text=J',
    isLive: false,
  },
  {
    id: '7',
    platform: 'chzzk',
    channelId: 'stu901',
    name: '고세구',
    profileImage: 'https://via.placeholder.com/100x100/00C853/ffffff?text=G',
    isLive: false,
  },
  {
    id: '8',
    platform: 'soop',
    channelId: 'vwx234',
    name: '비챤',
    profileImage: 'https://via.placeholder.com/100x100/2196F3/ffffff?text=B',
    isLive: false,
  },
  {
    id: '9',
    platform: 'chzzk',
    channelId: 'yza567',
    name: '징버거',
    profileImage: 'https://via.placeholder.com/100x100/00C853/ffffff?text=Z',
    isLive: false,
  },
  {
    id: '10',
    platform: 'soop',
    channelId: 'bcd890',
    name: '따효니',
    profileImage: 'https://via.placeholder.com/100x100/2196F3/ffffff?text=D',
    isLive: false,
  },
];


